layer_0: [4, -1, 4]
layer_1: [4, 2, -1]
layer_2:
  cv1: [4, 4, -2]
  cv2: [4, 3, 0]
  m.0:
    cv1: [4, 1, 1]
    cv2: [4, 3, 0]
layer_3: [4, 4, 1]
layer_4:
  cv1: [4, 2, 1]
  cv2: [4, 4, 1]
  m.0:
    cv1: [4, 4, 2]
    cv2: [4, 4, 2]
  m.1:
    cv1: [4, 4, 1]
    cv2: [4, 2, 2]
layer_5: [4, 5, 2]
layer_6:
  cv1: [4, 3, 2]
  cv2: [4, 4, 1]
  m.0:
    cv1: [4, 4, 2]
    cv2: [4, 4, 2]
  m.1:
    cv1: [4, 5, 1]
    cv2: [4, 3, 2]
layer_7: [4, 5, 2]
layer_8:
  cv1: [4, 3, 1]
  cv2: [4, 5, 1]
  m.0:
    cv1: [4, 4, 2]
    cv2: [4, 4, 1]
layer_9:
  cv1: [4, 4, 1]
  cv2: [4, 5, 1]
layer_12:
  cv1: [4, 3, 2]
  cv2: [4, 4, 1]
  m.0:
    cv1: [4, 4, 2]
    cv2: [4, 4, 2]
layer_15:
  cv1: [4, 4, 2]
  cv2: [4, 3, 2]
  m.0:
    cv1: [4, 4, 2]
    cv2: [4, 3, 2]
layer_16: [4, 4, 2]
layer_18:
  cv1: [4, 3, 2]
  cv2: [4, 4, 1]
  m.0:
    cv1: [4, 4, 1]
    cv2: [4, 3, 2]
layer_19: [4, 5, 2]
layer_21:
  cv1: [4, 3, 1]
  cv2: [4, 4, 1]
  m.0:
    cv1: [4, 4, 1]
    cv2: [4, 4, 1]
layer_22:
  cv2.0: [4, 4, 1]
  cv2.1: [4, 2, 0]
  cv2.2: [4, 4, -1]
  cv3.0: [4, 4, 1]
  cv3.1: [4, 3, 1]
  cv3.2: [4, 4, -1]
