layer_0: [8, 3, 8]
layer_1: [8, 6, 3]
layer_2:
  cv1: [8, 8, 2]
  cv2: [8, 7, 4]
  m.0:
    cv1: [8, 5, 5]
    cv2: [8, 7, 4]
layer_3: [8, 8, 5]
layer_4:
  cv1: [8, 6, 5]
  cv2: [8, 8, 5]
  m.0:
    cv1: [8, 8, 6]
    cv2: [8, 8, 6]
  m.1:
    cv1: [8, 8, 5]
    cv2: [8, 6, 6]
layer_5: [8, 9, 6]
layer_6:
  cv1: [8, 7, 6]
  cv2: [8, 8, 5]
  m.0:
    cv1: [8, 8, 6]
    cv2: [8, 8, 6]
  m.1:
    cv1: [8, 9, 5]
    cv2: [8, 7, 6]
layer_7: [8, 9, 6]
layer_8:
  cv1: [8, 7, 5]
  cv2: [8, 9, 5]
  m.0:
    cv1: [8, 8, 6]
    cv2: [8, 8, 5]
layer_9:
  cv1: [8, 8, 5]
  cv2: [8, 9, 5]
layer_12:
  cv1: [8, 7, 6]
  cv2: [8, 8, 5]
  m.0:
    cv1: [8, 8, 6]
    cv2: [8, 8, 6]
layer_15:
  cv1: [8, 8, 6]
  cv2: [8, 7, 6]
  m.0:
    cv1: [8, 8, 6]
    cv2: [8, 7, 6]
layer_16: [8, 8, 6]
layer_18:
  cv1: [8, 7, 6]
  cv2: [8, 8, 5]
  m.0:
    cv1: [8, 8, 5]
    cv2: [8, 7, 6]
layer_19: [8, 9, 6]
layer_21:
  cv1: [8, 7, 5]
  cv2: [8, 8, 5]
  m.0:
    cv1: [8, 8, 5]
    cv2: [8, 8, 5]
layer_22:
  cv2.0: [8, 8, 5]
  cv2.1: [8, 6, 4]
  cv2.2: [8, 8, 3]
  cv3.0: [8, 8, 5]
  cv3.1: [8, 7, 5]
  cv3.2: [8, 8, 3]
